-- Migration: Normalize missing tables and fix trade_proposals status enum
-- Date: 2026-03-30
-- Context: Audit found 6 tables used by runtime without versioned migrations,
--          plus trade_proposals CHECK constraint missing 3 status values.

-- =============================================================================
-- 1. Fix trade_proposals status CHECK constraint
--    Add: 'executing', 'dead_letter', 'cancelled'
-- =============================================================================

ALTER TABLE trade_proposals
  DROP CONSTRAINT IF EXISTS trade_proposals_status_check;

ALTER TABLE trade_proposals
  ADD CONSTRAINT trade_proposals_status_check CHECK (
    status IN (
      'draft', 'validated', 'approved', 'rejected',
      'executing', 'executed', 'partially_filled', 'error',
      'dead_letter', 'cancelled'
    )
  );

-- =============================================================================
-- 2. llm_trading_configs — LLM-generated config overrides for the quant engine
-- =============================================================================

CREATE TABLE IF NOT EXISTS llm_trading_configs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'superseded')),
  source TEXT NOT NULL DEFAULT 'llm_premarket',
  confidence_score DECIMAL(5, 2),
  values_clamped JSONB DEFAULT '[]'::jsonb,
  -- TradingConfigOverride fields
  buy_adx_min DECIMAL(5, 2),
  buy_entropy_max DECIMAL(5, 4),
  buy_rsi_max DECIMAL(5, 2),
  sell_rsi_min DECIMAL(5, 2),
  signal_cooldown_minutes INTEGER,
  sl_atr_multiplier DECIMAL(5, 2),
  tp_atr_multiplier DECIMAL(5, 2),
  risk_multiplier DECIMAL(5, 2),
  max_open_positions INTEGER,
  quant_symbols TEXT,
  reasoning TEXT DEFAULT '',
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  superseded_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_llm_trading_configs_status
  ON llm_trading_configs (status, created_at DESC);

-- =============================================================================
-- 3. llm_audit_reports — Daily post-market audits generated by LLM
-- =============================================================================

CREATE TABLE IF NOT EXISTS llm_audit_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  audit_date DATE NOT NULL UNIQUE,
  performance_summary JSONB,
  trade_reviews JSONB DEFAULT '[]'::jsonb,
  error_analysis TEXT DEFAULT '',
  market_events TEXT DEFAULT '',
  recommendations JSONB DEFAULT '[]'::jsonb,
  overall_grade TEXT DEFAULT 'C',
  model_used TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 4. llm_daily_briefs — Pre-market briefings
-- =============================================================================

CREATE TABLE IF NOT EXISTS llm_daily_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brief_date DATE NOT NULL,
  market_summary TEXT,
  symbol_analyses JSONB DEFAULT '[]'::jsonb,
  risk_assessment TEXT,
  fear_greed_value INTEGER,
  fear_greed_label TEXT,
  news_summary TEXT DEFAULT '',
  config_overrides JSONB,
  confidence_score DECIMAL(3, 2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_llm_daily_briefs_date
  ON llm_daily_briefs (brief_date DESC);

-- =============================================================================
-- 5. reconciliation_runs — Broker reconciliation tracking
-- =============================================================================

CREATE TABLE IF NOT EXISTS reconciliation_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  broker_adapter TEXT NOT NULL DEFAULT 'spot_testnet',
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'success', 'error')),
  orders_synced INTEGER DEFAULT 0,
  positions_synced INTEGER DEFAULT 0,
  divergences_found INTEGER DEFAULT 0,
  divergence_details JSONB DEFAULT '[]'::jsonb,
  actions_taken JSONB DEFAULT '[]'::jsonb,
  error_message TEXT,
  duration_ms INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reconciliation_runs_status
  ON reconciliation_runs (status, created_at DESC);

-- =============================================================================
-- 6. ml_training_runs — ML model training metadata
-- =============================================================================

CREATE TABLE IF NOT EXISTS ml_training_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  model_name TEXT NOT NULL DEFAULT 'lgb_logret',
  n_folds INTEGER,
  mean_sharpe DECIMAL(10, 4),
  mean_hit_rate DECIMAL(10, 4),
  mean_mae DECIMAL(10, 4),
  total_oos_samples INTEGER,
  symbols JSONB,
  train_days INTEGER,
  test_days INTEGER,
  hyperparams JSONB,
  fold_metrics JSONB,
  feature_columns JSONB,
  elapsed_seconds DECIMAL(10, 2),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- 7. ml_predictions — ML model predictions
-- =============================================================================

CREATE TABLE IF NOT EXISTS ml_predictions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol TEXT NOT NULL,
  open_time TIMESTAMPTZ NOT NULL,
  y_true DECIMAL(15, 8),
  y_pred DECIMAL(15, 8),
  fold INTEGER,
  run_id UUID REFERENCES ml_training_runs(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ml_predictions_open_time
  ON ml_predictions (open_time DESC);

CREATE INDEX IF NOT EXISTS idx_ml_predictions_symbol_time
  ON ml_predictions (symbol, open_time DESC);
